site_name: PARC
theme: readthedocs
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - toc:
        permalink: True
        separator: "_"
plugins:
    - search
nav:
    - 'Competition Overview': 'competition-overview/index.md'

    - 'Competition Instruction': 
        - 'Phase 1: Simulation':
            - 'Introduction': 'phase1-instructions/index.md'
            - 'Task 1: Sidewalk following': 'phase1-instructions/task1.md'
            - 'Task 2: Traffic sign detection and recognition': 'phase1-instructions/task2.md'
            - 'Task 3: Go-to-goal navigation': 'phase1-instructions/task3.md'
            - 'How to Submit': 'phase1-instructions/how-to-submit.md'
        - 'Phase 2: Physical Robot': 'phase2-instructions/index.md'

    - 'Getting Started Tutorials':
        - 'Setting up your PC': 'getting-started/setting-up-your-pc/index.md'
        - 'Setting up your Workspace': 'getting-started/setting-up-your-workspace/index.md'
        - 'Introduction to ROS': 'getting-started/understanding-ros.md'

extra_css: [theme_override.css]
